### ISSUE TITLE
v1.1.0 requires ES2015 (ES6) default argument feature

### ISSUE THREAD

**Issue by bochkarev-artem** [bd808/php-unserialize-js#17]
While running this along with symfony app i get this error:
```
Unexpected token operator «=», expected punc «,» [~/phpunserialize/phpUnserialize.js:80,0]

[Symfony\Component\Process\Exception\ProcessFailedException]
  The command "'node_modules/.bin/webpack' '--config' '~/var/cache/prod/webpack.config.js'" failed.

  Exit Code: 2(Misuse of shell builtins)
```

By looking at line 80, i see default parameter `expect = '"'`
When removing `= '"'` it works again. Issue appeared after upgrading from v1.0.1 to v1.1.0

**Comment by bochkarev-artem** [comment]
I think its related with: https://github.com/bd808/php-unserialize-js/commit/6aedd57e3b6d7a59edffe5a9c1d6ac3b0101c79c
@bd808 @bd808

**Comment by bd808** [comment]
Default arguments are an ES2015 (sometimes known as ES6) feature. My brain skipped over that when working on  6aedd57. In this case it is a thing that is pretty easy to fix to push the default down into the method body.
