### ISSUE TITLE
Is there a way to continue past parsing errors?

### ISSUE THREAD

**Issue by slgoldberg** [bd808/php-unserialize-js#4]
This is an awesome function and is very helpful in my handling raw data that was previously serialized by php directly into my legacy mysql database -- so thanks very much for this.

But as with all legacy data, there are errors in the encoded data (probably having to do with character set issues, pre-utf8).  I'm totally fine to throw away such data, but unfortunately this function will abort execution (at least in V8 i.e. on Chrome) and give a stack trace when it first hits something it doesn't know about.

Is there any way to make it more "robust" in the face of failures?  Can't it just be configured to continue past the failure and return the empty string instead of an error?  I have a call to phpUnserialize() deep within a huge loop that loops over a big array of data read from the database. But my JS code stops running entirely when the first parsing error is hit.  I would happily just check for null or empty-string and ignore unparseable values in that case, but I can't seem to work out how to do it.

As a relative newbie to JS, I'm unclear on how to do this myself, and wondering if you can either tell me or just make the modification to your code if it's possible to do so with a parameter, e.g. "phpUnserialize(serializedString, true)" where the second parameter is something like "ignoreFailures"?  I tried hacking my own version up but the logic eludes me since again, I'm not really a JS expert.

Thanks very much.

**Comment by bd808** [comment]
@slgoldberg Give the feature/state-on-exception branch a try when you get a chance and see if it helps with your encoding recovery issues. I added a `state` member to the exception that is thrown when decoding an array or object fails.

The strings you gave in the previous log output are definitely suffering from mixed encoding problems. phpUnserialize assumes that all input will be UTF-8 encoded and additionally assumes that the PHP environment that generated the serialized representation was also using UTF-8 as the default encoding for strings.
